baseurl = "https://grantcooksey.github.io/MyersSportsMedicine"
languageCode = "en-us"
title = "Myers Sports Medicine & Orthopaedic Center"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true
relativeurls = true

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[Params]
    featuredImage = "images/myers-operating.jpg"
    logo = "images/logo.jpg"
